In [1]:
import os

from google.cloud import vision
from google.cloud.vision_v1 import types

import pandas as pd
import cv2
import numpy as np
import json

import imutils
import matplotlib.pyplot as plt
from scipy.signal import find_peaks

import random
import logging

from Read import Download,Crop,PosiLetter, Vision, AddData, GetPosi, ExtractData, Show, Organize

#Load index list
Year='1941'
Showa='16'

In [2]:
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Environment\\GoogleVision\\practice-302516-01e0f7245b03.json'
# Instantiates a client
client = vision.ImageAnnotatorClient()

In [6]:
#Load Data Frame
path="C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Processed_Data\\"+str(Year)+"\\DataFrame_PositionFin.json"
with open(path, 'r') as j:
     dta = json.loads(j.read())

df = pd.read_csv(r'C:/Users/Keitaro Ninomiya/Box/Research Notes (keitaro2@illinois.edu)/Tokyo_Jobs/Processed_Data/Index/S'+str(Showa)+'_v2.csv')
df=df.drop(df.columns[0], axis=1)

filepath="C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Office_Level\\"+Year

# 1. Sample Code with single unit

In [70]:
n=44
print(n)
Row=df.iloc[n]
Dept,Office=Row['Dept'],Row['Office']
Posi=GetPosi(Year,dta,Dept,Office)
Dept,Office,Posi

44

('厚生局', '軍事援護課', 'Clerk1')

In [71]:
dta[Year][Dept][Office]

{'StrPage': 40,
 'StrLocation': 320,
 'StrPart': 'Btm',
 'EndPage': 41,
 'EndPart': 'Top',
 'EndLocation': 230,
 'Page_Range': [40, 41],
 'Positions': {'Manager': {'StrPage': 1.0,
   'StrLocation': 303.0,
   'Part': '1',
   'EndLocation': 150.0,
   'EndPage': 1.0},
  'Clerk1': {'StrPage': 1.0,
   'StrLocation': 150.0,
   'Part': '1',
   'EndLocation': 0.0,
   'EndPage': 41.0}}}

In [72]:
MainDF=pd.DataFrame(columns=['Dept', 'Office','Posi','Page','StartPosi','FemaleCount','Size'])
Part=int(dta[Year][Dept][Office]['Positions'][Posi]['Part'])
StrPage=int(dta[Year][Dept][Office]['Positions'][Posi]['StrPage'])
EndPage=int(dta[Year][Dept][Office]['Positions'][Posi]['EndPage'])
PageRange=range(1,StrPage-EndPage+2)
try:    
    for Page in PageRange:
        df1={'Dept':'', 'Office':'','Posi':'','Page':''}
        df1['Dept'],df1['Office'],df1['Posi'],df1['Page']=Dept,Office,Posi,Page
        df1=pd.DataFrame([df1])
        
        # Download Image
        image=Download(filepath,Dept,Office,Posi,Page)
        # Separates Image into Parts
        ImgList=Crop(image,client,Posi,Part,Page)
        StartPosi=ImgList[3]
        Show(ImgList)
        #Extract Data
        DictData=ExtractData(ImgList,client)
        #Aggregate data
        Data=Organize(DictData)
        df2 = pd.DataFrame([Data])
        
        df = pd.concat([df1, df2],axis=1)
        MainDF=pd.concat([MainDF,df], ignore_index = True)
        MainDF.reset_index()
except FileNotFoundError as e:
    print(f"File not found!")

In [74]:
Page=1
image=Download(filepath,Dept,Office,Posi,2)
ImgList=Crop(image,client,Posi,Part,Page)
StartPosi=ImgList[3]

Show(ImgList)

TypeError: 'NoneType' object is not subscriptable

In [78]:
cv2.imshow('',image)
cv2.waitKey(0)

-1

In [8]:
IndexList=[80,171,21,2,92,87,152,87]
np.sort(IndexList)

array([  2,  21,  80,  87,  87,  92, 152, 171])

# 2. Main Code

In [80]:
MainDF=pd.DataFrame(columns=['Dept', 'Office','Posi','Page','StartPosi','FemaleCount','Size'])
NoImageOffice=pd.DataFrame(columns=['Dept', 'Office','Posi','Page'])
IndexError=pd.DataFrame(columns=['Dept', 'Office','Posi','Page'])

for n in random.sample(range(0,len(df)),50):
    Row=df.iloc[n]
    Dept,Office=Row['Dept'],Row['Office']
    display(n,Dept,Office)
    try:
        Posi=GetPosi(Year,dta,Dept,Office)
    except:
        continue
    if Posi=='NA':
        dict = {'Dept':[Dept],
            'Office':[Office],
            'Posi':['NoOffice'],
            'Page':['NoOffice'],
            'StartPosi':['NoOffice'],
            'FemaleCount':['NoOffice'],
            'Size':['NoOffice']
            }
        df1 = pd.DataFrame(dict)        
        MainDF = pd.concat([MainDF, df1], ignore_index = True)
        
    if Posi!='Worker':
        continue

    Part=int(dta[Year][Dept][Office]['Positions'][Posi]['Part'])
    StrPage=int(dta[Year][Dept][Office]['Positions'][Posi]['StrPage'])
    EndPage=int(dta[Year][Dept][Office]['Positions'][Posi]['EndPage'])
    PageRange=range(1,StrPage-EndPage+2)
    try:    
        for Page in PageRange:
            df1={'Dept':'', 'Office':'','Posi':'','Page':''}
            df1['Dept'],df1['Office'],df1['Posi'],df1['Page']=Dept,Office,Posi,Page
            df1=pd.DataFrame([df1])

            # Download Image
            image=Download(filepath,Dept,Office,Posi,Page)
            # Separates Image into Parts
            ImgList=Crop(image,client,Posi,Part,Page)
            StartPosi=ImgList[3]
            
            #Extract Data
            DictData=ExtractData(ImgList,client)
            #Aggregate data
            Data=Organize(DictData)
            df2 = pd.DataFrame([Data])

            NewDF = pd.concat([df1, df2],axis=1)
            print(n)
            display(NewDF)
            MainDF=pd.concat([MainDF,NewDF], ignore_index = True)
            MainDF.reset_index()
    except FileNotFoundError as e:
        data={'Dept':[Dept],'Office':[Office],'Posi':[Posi],'Page':[Page]}
        df3=pd.DataFrame.from_dict(data)
        NoImageOffice=pd.concat([NoImageOffice,df3])
        continue
    except:
        data={'Dept':[Dept],'Office':[Office],'Posi':[Posi],'Page':[Page]}
        df3=pd.DataFrame.from_dict(data)
        IndexError=pd.concat([NoImageOffice,df3])
        continue

76

'厚生局'

'病院'

52

'厚生局'

'清掃部'

19

'財務局'

'建築部'

235

'区役所'

'中野区役所'

206

'電気局'

'電燈部'

204

'電気局'

'電燈部'

144

'港湾局'

'庶務課'

212

'区役所'

'麹町区役所'

12

'財務局'

'主計課'

64

'厚生局'

'清掃部'

151

'水道局'

'庶務課'

164

'電気局'

'会計課'

2

'総務局'

'人事課'

92

'経済局'

'庶務課'

141

'土木局'

'土木出張所'

243

'区役所'

'向島区役所'

41

'教育局'

'学校体育課'

4

'総務局'

'議案課'

83

'厚生局'

'療養所'

218

'区役所'

'赤坂区役所'

87

'養育院'

'医務課'

166

'電気局'

'運輸部'

89

'養育院'

'巣鴨分院'

112

'土木局'

'土木出張所'

250

'東京市健康保険組合'

'東京市健康保険組合病院'

79

'厚生局'

'病院'

15

'財務局'

'用品課'

20

'財務局'

'建築部'

153

'水道局'

'営業課'

91

'養育院'

'萩山賓務学校'

39

'教育局'

'青年教育課'

171

'電気局'

'運輸部'

248

'市会事務局'

'議事課'

63

'厚生局'

'清掃部'

245

'区役所'

'葛飾区役所'

236

'区役所'

'杉並区役所'

46

'厚生局'

'保護課'

32

'防衛局'

'防衛課'

137

'土木局'

'土木出張所'

131

'土木局'

'土木出張所'

174

'電気局'

'運輸部'

244

'区役所'

'城東区役所'

43

'厚生局'

'庶務課'

55

'厚生局'

'清掃部'

240

'区役所'

'王子区役所'

214

'区役所'

'日本橋区役所'

3

'総務局'

'吏務課'

125

'土木局'

'土木出張所'

104

'土木局'

'道路建設課'

95

'経済局'

'農漁課'

In [79]:
dta

{'1941': {'Admin': {'秘書課': {'Starting_Page': 3,
    'StrLocation': 119,
    'StrPart': 'Top',
    'EndPage': 4,
    'EndPart': 'Top',
    'EndLocation': 356,
    'Page_Range': [3, 4]}},
  '中央卸売市場': {'管理課': {'StrPage': 86,
    'StrLocation': 355,
    'StrPart': 'Top',
    'EndPage': 86,
    'EndLocation': 255,
    'Page_Range': [86],
    'EndPart': 'Btm',
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 86}}},
   '業務課': {'StrPage': 86,
    'StrLocation': 255,
    'StrPart': 'Btm',
    'EndPage': 87,
    'EndLocation': 500,
    'Page_Range': [86, 87],
    'EndPart': 'Btm',
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 87}}},
   '副収入役室': {'StrPage': 87,
    'StrLocation': 500,
    'EndPage': 87,
    'EndLocation': 245,
    'Page_Range': [87],
    'EndPart': 'Btm',
    'StrPart': 'Btm',
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 87}}}},
  '交通調整部': {'第一調整課': {'StrPage': 146,
    'StrLocation': 440,
    'EndPage': 147,
    'EndLocation': 500,
    'Page_Range': [146, 147],
    'StrPart': 'Btm',
    'EndPart': 'Top'},
   '第二調整課': {'StrPage': 147,
    'StrLocation': 500,
    'EndPage': 147,
    'EndPart': 'Top',
    'EndLocation': 195,
    'Page_Range': [147],
    'StrPart': 'Top'},
   '技術課': {'StrPage': 147,
    'StrLocation': 195,
    'StrPart': 'Top',
    'EndPage': 147,
    'EndLocation': 460,
    'Page_Range': [147],
    'EndPart': 'Btm'}},
  '厚生局': {'庶務課': {'StrPage': 39,
    'StrLocation': 330,
    'StrPart': 'Btm',
    'EndPage': 40,
    'EndLocation': 320,
    'Page_Range': [39, 40],
    'EndPart': 'Btm',
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 308.0,
      'Part': '1',
      'EndLocation': 480.0,
      'EndPage': 2.0},
     'Clerk1': {'StrPage': 2.0,
      'StrLocation': 480.0,
      'Part': '1',
      'EndLocation': 128.0,
      'EndPage': 2.0},
     'Engineer2': {'StrPage': 2.0,
      'StrLocation': 128.0,
      'Part': '2',
      'EndLocation': 108.0,
      'EndPage': 2.0},
     'Worker': {'StrPage': 2.0,
      'StrLocation': 108.0,
      'Part': '4',
      'EndLocation': 0.0,
      'EndPage': 40.0}}},
   '軍事援護課': {'StrPage': 40,
    'StrLocation': 320,
    'StrPart': 'Btm',
    'EndPage': 41,
    'EndPart': 'Top',
    'EndLocation': 230,
    'Page_Range': [40, 41],
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 303.0,
      'Part': '1',
      'EndLocation': 150.0,
      'EndPage': 1.0},
     'Clerk1': {'StrPage': 1.0,
      'StrLocation': 150.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 41.0}}},
   '児童課': {'StrPage': 41,
    'StrLocation': 230,
    'StrPart': 'Top',
    'EndPage': 42,
    'EndPart': 'Btm',
    'EndLocation': 150,
    'Page_Range': [41, 42],
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 214.0,
      'Part': '1',
      'EndLocation': 407.0,
      'EndPage': 2.0},
     'Engineer1': {'StrPage': 2.0,
      'StrLocation': 407.0,
      'Part': '1',
      'EndLocation': 229.0,
      'EndPage': 2.0},
     'Clerk1': {'StrPage': 2.0,
      'StrLocation': 229.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 42.0}}},
   '保護課': {'StrPage': 42,
    'StrLocation': 150,
    'StrPart': 'Btm',
    'EndPage': 46,
    'EndPart': 'Top',
    'EndLocation': 104,
    'Page_Range': [42, 43, 44, 45, 46],
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 131.0,
      'Part': '1',
      'EndLocation': 0,
      'EndPage': 46}}},
   '福利課': {'StrPage': 46,
    'StrLocation': 104,
    'StrPart': 'Top',
    'EndPage': 49,
    'EndPart': 'Btm',
    'EndLocation': 270,
    'Page_Range': [46, 47, 48, 49],
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 75.0,
      'Part': '1',
      'EndLocation': 68.0,
      'EndPage': 1.0},
     'Leader': {'StrPage': 1.0,
      'StrLocation': 68.0,
      'Part': '1',
      'EndLocation': 487.0,
      'EndPage': 3.0},
     'Engineer1': {'StrPage': 3.0,
      'StrLocation': 487.0,
      'Part': '3',
      'EndLocation': 413.0,
      'EndPage': 4.0},
     'Clerk1': {'StrPage': 4.0,
      'StrLocation': 413.0,
      'Part': '1',
      'EndLocation': 347.0,
      'EndPage': 4.0},
     'Engineer2': {'StrPage': 4.0,
      'StrLocation': 347.0,
      'Part': '1',
      'EndLocation': 80.0,
      'EndPage': 4.0},
     'Checker': {'StrPage': 4.0,
      'StrLocation': 80.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 49.0}}},
   '衛生課': {'StrPage': 49,
    'StrLocation': 270,
    'StrPart': 'Btm',
    'EndPage': 54,
    'EndPart': 'Top',
    'EndLocation': 426,
    'Page_Range': [49, 50, 51, 52, 53, 54],
    'Positions': {'Engineer1': {'StrPage': 1.0,
      'StrLocation': 251.0,
      'Part': '2',
      'EndLocation': 211.0,
      'EndPage': 1.0},
     'Manager': {'StrPage': 1.0,
      'StrLocation': 211.0,
      'Part': '1',
      'EndLocation': 390.0,
      'EndPage': 5.0},
     'Pharmacist': {'StrPage': 5.0,
      'StrLocation': 390.0,
      'Part': '1',
      'EndLocation': 165.0,
      'EndPage': 5.0},
     'Nursehead': {'StrPage': 5.0,
      'StrLocation': 165.0,
      'Part': '1',
      'EndLocation': 157.0,
      'EndPage': 5.0},
     'Worker': {'StrPage': 5.0,
      'StrLocation': 157.0,
      'Part': '4',
      'EndLocation': 0.0,
      'EndPage': 54.0}}},
   '防疫課': {'StrPage': 54,
    'StrLocation': 426,
    'StrPart': 'Top',
    'EndPage': 55,
    'EndPart': 'Top',
    'EndLocation': 183,
    'Page_Range': [54, 55]}},
  '土木局': {'庶務課': {'StrPage': 87,
    'StrLocation': 245,
    'StrPart': 'Btm',
    'EndPage': 88,
    'EndLocation': 250,
    'Page_Range': [87, 88],
    'EndPart': 'Btm',
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 88}}},
   '道路管理課': {'StrPage': 88,
    'StrLocation': 250,
    'StrPart': 'Btm',
    'EndPage': 90,
    'EndLocation': 40,
    'Page_Range': [88, 89, 90],
    'EndPart': 'Top',
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 90}}},
   '道路建設課': {'StrPage': 90,
    'StrLocation': 40,
    'EndPage': 91,
    'EndLocation': 239,
    'Page_Range': [90, 91],
    'EndPart': 'Btm',
    'StrPart': 'Top',
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 91}}},
   '橋梁課': {'StrPage': 91,
    'StrLocation': 239,
    'StrPart': 'Btm',
    'EndPage': 92,
    'EndPart': 'Top',
    'EndLocation': 100,
    'Page_Range': [91, 92],
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 92}}},
   '河川課': {'StrPage': 92,
    'StrLocation': 100,
    'StrPart': 'Top',
    'EndPage': 93,
    'EndLocation': 303,
    'Page_Range': [92, 93],
    'EndPart': 'Top',
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 93}}},
   '治水工事課': {'StrPage': 93,
    'StrLocation': 303,
    'EndPage': 94,
    'EndPart': 'Top',
    'EndLocation': 440,
    'Page_Range': [93, 94],
    'StrPart': 'Top',
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 94}}},
   '土木試験所': {'StrPage': 94,
    'StrLocation': 440,
    'StrPart': 'Top',
    'EndPage': 94,
    'EndPart': 'Top',
    'EndLocation': 190,
    'Page_Range': [94],
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 94}}},
   '土木出張所': {'StrPage': 94,
    'StrLocation': 190,
    'StrPart': 'Top',
    'EndPage': 101,
    'EndPart': 'Top',
    'EndLocation': 402,
    'Page_Range': [94, 95, 96, 97, 98, 99, 100, 101],
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 101}}}},
  '市民局': {'庶務課': {'StrPage': 24,
    'StrLocation': 358,
    'StrPart': 'Top',
    'EndPage': 24,
    'EndLocation': 448,
    'Page_Range': [24],
    'EndPart': 'Btm',
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 24}}},
   '区政課': {'StrPage': 24,
    'StrLocation': 448,
    'StrPart': 'Btm',
    'EndPage': 24,
    'EndLocation': 110,
    'Page_Range': [24],
    'EndPart': 'Top',
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 24}}},
   '町会課': {'StrPage': 24,
    'StrLocation': 110,
    'EndPage': 25,
    'EndPart': 'Top',
    'EndLocation': 222,
    'Page_Range': [24, 25],
    'StrPart': 'Btm',
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 89.0,
      'Part': '1',
      'EndLocation': 255.0,
      'EndPage': 1.0},
     'Clerk1': {'StrPage': 1.0,
      'StrLocation': 255.0,
      'Part': '1',
      'EndLocation': 122.0,
      'EndPage': 2.0},
     'Worker': {'StrPage': 2.0,
      'StrLocation': 122.0,
      'Part': '4',
      'EndLocation': 44.0,
      'EndPage': 2.0},
     'Outsource': {'StrPage': 2.0,
      'StrLocation': 44.0,
      'Part': '2',
      'EndLocation': 0.0,
      'EndPage': 25.0}}},
   '體力課': {'StrPage': 25,
    'StrLocation': 222,
    'StrPart': 'Top',
    'EndPage': 25,
    'EndLocation': 172,
    'Page_Range': [25],
    'EndPart': 'Btm',
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 209.0,
      'Part': '1',
      'EndLocation': 0,
      'EndPage': 25}}},
   '公園課': {'StrPage': 25,
    'StrLocation': 172,
    'StrPart': 'Btm',
    'EndPage': 28,
    'EndLocation': 500,
    'Page_Range': [25, 26, 27, 28],
    'EndPart': 'Btm',
    'Positions': {'理事': {'StrPage': 1.0,
      'StrLocation': 159.0,
      'Part': '1',
      'EndLocation': 123.0,
      'EndPage': 1.0},
     'Manager': {'StrPage': 1.0,
      'StrLocation': 123.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 28.0}}}},
  '建築部': {'管理課': {'StrPage': 20,
    'StrLocation': 436,
    'StrPart': 'Top',
    'EndPage': 20,
    'EndLocation': 458,
    'Page_Range': [20],
    'EndPart': 'Btm',
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 430.0,
      'Part': '1',
      'EndLocation': 350.0,
      'EndPage': 1.0},
     'Engineer1': {'StrPage': 1.0,
      'StrLocation': 350.0,
      'Part': '1',
      'EndLocation': 265.0,
      'EndPage': 1.0},
     'Clerk1': {'StrPage': 1.0,
      'StrLocation': 265.0,
      'Part': '2',
      'EndLocation': 160.0,
      'EndPage': 1.0},
     'Engineer2': {'StrPage': 1.0,
      'StrLocation': 160.0,
      'Part': '2',
      'EndLocation': 95.0,
      'EndPage': 1.0},
     'Worker': {'StrPage': 1.0,
      'StrLocation': 95.0,
      'Part': '3',
      'EndLocation': 0.0,
      'EndPage': 20.0}}},
   '営繕課': {'StrPage': 20,
    'StrLocation': 458,
    'StrPart': 'Btm',
    'EndPage': 21,
    'EndLocation': 151,
    'Page_Range': [20, 21],
    'EndPart': 'Top',
    'Positions': {'Engineer1': {'StrPage': 1.0,
      'StrLocation': 440.0,
      'Part': '1',
      'EndLocation': 237.0,
      'EndPage': 1.0},
     'Clerk1': {'StrPage': 1.0,
      'StrLocation': 237.0,
      'Part': '1',
      'EndLocation': 190.0,
      'EndPage': 1.0},
     'Engineer2': {'StrPage': 1.0,
      'StrLocation': 190.0,
      'Part': '1',
      'EndLocation': 200.0,
      'EndPage': 2.0},
     'Worker': {'StrPage': 2.0,
      'StrLocation': 200.0,
      'Part': '4',
      'EndLocation': 50.0,
      'EndPage': 2.0},
     'Outsource': {'StrPage': 2.0,
      'StrLocation': 50.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 21.0}}},
   '学校営業課': {'StrPage': 21,
    'StrLocation': 151,
    'EndPage': 23,
    'EndLocation': 477,
    'Page_Range': [21, 22, 23],
    'EndPart': 'Btm',
    'StrPart': 'Top',
    'Positions': {'Engineer1': {'StrPage': 1.0,
      'StrLocation': 138.0,
      'Part': '1',
      'EndLocation': 270.0,
      'EndPage': 3.0},
     'Clerk1': {'StrPage': 3.0,
      'StrLocation': 270.0,
      'Part': '2',
      'EndLocation': 252.0,
      'EndPage': 3.0},
     'Engineer2': {'StrPage': 3.0,
      'StrLocation': 252.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 23.0}}},
   '装置課': {'StrPage': 23,
    'StrLocation': 477,
    'StrPart': 'Btm',
    'EndPage': 24,
    'EndPart': 'Top',
    'EndLocation': 358,
    'Page_Range': [23, 24],
    'Positions': {'Engineer1': {'StrPage': 1.0,
      'StrLocation': 475.0,
      'Part': '1',
      'EndLocation': 320.0,
      'EndPage': 1.0},
     'Clerk1': {'StrPage': 1.0,
      'StrLocation': 320.0,
      'Part': '2',
      'EndLocation': 308.0,
      'EndPage': 1.0},
     'Engineer2': {'StrPage': 1.0,
      'StrLocation': 308.0,
      'Part': '1',
      'EndLocation': 139.0,
      'EndPage': 1.0},
     'Worker': {'StrPage': 1.0,
      'StrLocation': 139.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 24.0}}}},
  '教育局': {'庶務課': {'StrPage': 33,
    'StrLocation': 231,
    'StrPart': 'Btm',
    'EndPage': 34,
    'EndLocation': 223,
    'Page_Range': [33, 34],
    'EndPart': 'Top',
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 217.0,
      'Part': '1',
      'EndLocation': 0,
      'EndPage': 34}}},
   '学校職員課': {'StrPage': 34,
    'StrLocation': 223,
    'EndPage': 34,
    'EndLocation': 320,
    'Page_Range': [34],
    'EndPart': 'Btm',
    'StrPart': 'Top',
    'Positions': {'nan': {'StrPage': None,
      'StrLocation': None,
      'Part': None,
      'EndLocation': 0,
      'EndPage': 34}}},
   '学務課': {'StrPage': 34,
    'StrLocation': 320,
    'StrPart': 'Btm',
    'EndPage': 35,
    'EndLocation': 380,
    'Page_Range': [34, 35],
    'EndPart': 'Top',
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 292.0,
      'Part': '1',
      'EndLocation': 158.0,
      'EndPage': 1.0},
     'Clerk1': {'StrPage': 1.0,
      'StrLocation': 158.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 35.0}}},
   '視学課': {'StrPage': 35,
    'StrLocation': 380,
    'EndPage': 36,
    'EndPart': 'Top',
    'EndLocation': 260,
    'Page_Range': [35, 36],
    'StrPart': 'Top',
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 364.0,
      'Part': '1',
      'EndLocation': 252.0,
      'EndPage': 1.0},
     'Inspector': {'StrPage': 1.0,
      'StrLocation': 252.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 36.0}}},
   '青年教育課': {'StrPage': 36,
    'StrLocation': 260,
    'StrPart': 'Top',
    'EndPage': 37,
    'EndLocation': 476,
    'Page_Range': [36, 37],
    'EndPart': 'Top',
    'Positions': {'Clerk1': {'StrPage': 2.0,
      'StrLocation': 292.0,
      'Part': '1',
      'EndLocation': 201.0,
      'EndPage': 2.0},
     'Worker': {'StrPage': 2.0,
      'StrLocation': 201.0,
      'Part': '2',
      'EndLocation': 165.0,
      'EndPage': 2.0},
     'Outsource': {'StrPage': 2.0,
      'StrLocation': 165.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 37.0}}},
   '社会教育課': {'StrPage': 37,
    'StrLocation': 476,
    'EndPage': 38,
    'EndPart': 'Top',
    'EndLocation': 345,
    'Page_Range': [37, 38],
    'StrPart': 'Top',
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 456.0,
      'Part': '1',
      'EndLocation': 178.0,
      'EndPage': 1.0},
     'Clerk1': {'StrPage': 1.0,
      'StrLocation': 178.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 38.0}}},
   '学校体育課': {'StrPage': 38,
    'StrLocation': 345,
    'StrPart': 'Top',
    'EndPage': 39,
    'EndPart': 'Btm',
    'EndLocation': 365,
    'Page_Range': [38, 39],
    'Positions': {'Lecturer': {'StrPage': 2.0,
      'StrLocation': 105.0,
      'Part': '2',
      'EndLocation': 63.0,
      'EndPage': 2.0},
     'Clerk1': {'StrPage': 2.0,
      'StrLocation': 63.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 39.0}}},
   '教育研究所': {'StrPage': 39,
    'StrLocation': 365,
    'StrPart': 'Top',
    'EndPage': 39,
    'EndLocation': 330,
    'Page_Range': [39],
    'EndPart': 'Btm',
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 336.0,
      'Part': '1',
      'EndLocation': 308.0,
      'EndPage': 1.0},
     'Lecturer': {'StrPage': 1.0,
      'StrLocation': 308.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 39.0}}}},
  '水道局': {'庶務課': {'StrPage': 124,
    'StrLocation': 490,
    'StrPart': 'Top',
    'EndPage': 124,
    'EndLocation': 428,
    'Page_Range': [124],
    'EndPart': 'Btm'},
   '会計課': {'StrPage': 105,
    'StrLocation': 171,
    'StrPart': 'Btm',
    'EndPage': 106,
    'EndPart': 'Top',
    'EndLocation': 190,
    'Page_Range': [105, 106],
    'Positions': {'Leader': {'StrPage': 1.0,
      'StrLocation': 168.0,
      'Part': '1',
      'EndLocation': 281.0,
      'EndPage': 2.0},
     'Manager': {'StrPage': 2.0,
      'StrLocation': 281.0,
      'Part': '1',
      'EndLocation': 209.0,
      'EndPage': 2.0},
     'Clerk1': {'StrPage': 2.0,
      'StrLocation': 209.0,
      'Part': '1',
      'EndLocation': 75.0,
      'EndPage': 2.0},
     'Worker': {'StrPage': 2.0,
      'StrLocation': 75.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 106.0}}},
   '営業課': {'StrPage': 106,
    'StrLocation': 190,
    'StrPart': 'Top',
    'EndPage': 116,
    'EndPart': 'Btm',
    'EndLocation': 240,
    'Page_Range': [106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116],
    'Positions': {'Manager': {'StrPage': 1.0,
      'StrLocation': 170.0,
      'Part': '1',
      'EndLocation': 544.0,
      'EndPage': 3.0},
     'Engineer1': {'StrPage': 3.0,
      'StrLocation': 544.0,
      'Part': '1',
      'EndLocation': 150.0,
      'EndPage': 3.0},
     'Clerk1': {'StrPage': 3.0,
      'StrLocation': 150.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 116.0}}},
   '給水課': {'StrPage': 116,
    'StrLocation': 240,
    'StrPart': 'Btm',
    'EndPage': 118,
    'EndLocation': 70,
    'Page_Range': [116, 117, 118],
    'EndPart': 'Top',
    'Positions': {'Leader': {'StrPage': 1.0,
      'StrLocation': 210.0,
      'Part': '1',
      'EndLocation': 220.0,
      'EndPage': 1.0},
     'Engineer1': {'StrPage': 1.0,
      'StrLocation': 220.0,
      'Part': '1',
      'EndLocation': 250.0,
      'EndPage': 2.0},
     'Clerk1': {'StrPage': 2.0,
      'StrLocation': 250.0,
      'Part': '1',
      'EndLocation': 285.0,
      'EndPage': 3.0},
     'Worker': {'StrPage': 3.0,
      'StrLocation': 285.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 118.0}}},
   '計書課': {'StrPage': 118,
    'StrLocation': 70,
    'EndPage': 119,
    'EndPart': 'Top',
    'EndLocation': 403,
    'Page_Range': [118, 119],
    'StrPart': 'Top',
    'Positions': {'Manager': {'StrPage': 2.0,
      'StrLocation': 481.0,
      'Part': '2',
      'EndLocation': 441.0,
      'EndPage': 2.0},
     'Engineer1': {'StrPage': 2.0,
      'StrLocation': 441.0,
      'Part': '1',
      'EndLocation': 281.0,
      'EndPage': 2.0},
     'Clerk1': {'StrPage': 2.0,
      'StrLocation': 281.0,
      'Part': '1',
      'EndLocation': 232.0,
      'EndPage': 2.0},
     'Engineer2': {'StrPage': 2.0,
      'StrLocation': 232.0,
      'Part': '1',
      'EndLocation': 0.0,
      'EndPage': 119.0}}},
   '拡張課': {'StrPage': 119,
    'StrLocation': 403,
    'StrPart': 'Top',
    'EndPage': 123,
    'EndLocation': 180,
    'Page_Range': [119, 120, 121, 122, 123],
    'EndPart': 'Btm'},
   '小河内貯水池建設事務所': {'StrPage': 123,
    'StrLocation': 180,
    'StrPart': 'Btm',
    'EndPage': 121,
    'EndPart': 'Top',
    'EndLocation': 505,
    'Page_Range': []},
   '下水課': {'StrPage': 121,
    'StrLocation': 505,
    'StrPart': 'Top',
    'EndPage': 124,
    'EndPart': 'Top',
    'EndLocation': 490,
    'Page_Range': [121, 122, 123, 124],

# 3. Save Data

In [ ]:
save_path="C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Processed_Data\\"+str(Year)
os.chdir(save_path)
MainDF.to_csv('Proto.csv', index = False, encoding="utf-8")

In [6]:
display(NoImageOffice)
display(IndexError)

       Dept  Office    Posi Page
0       経理局     会計課  Worker    1
0       経理局     収納課  Worker    2
0       建築部     営繕課  Worker    2
0     戦時生活局     町会課  Worker    2
0       健民局     防疫課  Worker    2
0       健民局     厚生課  Worker    4
0       教育局   学校体育課  Worker    2
0       教育局  日比谷図書館  Worker    2
0       防衛局   防火改修課  Worker    2
0       土木局   道路管理課  Worker    2
0       水道局     下水課  Worker    1
0  利根川水道建設所     技術課  Worker    2
0       事業部      病院  Worker    2
0       清掃部     作業課  Worker    1

       Dept  Office    Posi Page
0       経理局     会計課  Worker    1
0       経理局     収納課  Worker    2
0       建築部     営繕課  Worker    2
0     戦時生活局     町会課  Worker    2
0       健民局     防疫課  Worker    2
0       健民局     厚生課  Worker    4
0       教育局   学校体育課  Worker    2
0       教育局  日比谷図書館  Worker    2
0       防衛局   防火改修課  Worker    2
0       土木局   道路管理課  Worker    2
0       水道局     下水課  Worker    1
0  利根川水道建設所     技術課  Worker    2
0       事業部      病院  Worker    2
0     電気研究所     研究課  Worker    1

# 4. Check Source of error

- Estimated sample with starting position correctly detected.

In [94]:
len(df)*sum(df1['StartPosi']=='True')/len(df1)

0.0

In [95]:
len(df)*sum(df1['StartPosi']=='False')/len(df1)

269.0

- Missing Data

In [96]:
sum(df1['Posi']=='NoOffice')/len(df1)

0.0

- Unknown Error

In [97]:
sum(df1['Posi']=='Error')/len(df1)

0.0